// Ambient module declarations for non-TypeScript imports.
// next-env.d.ts is auto-generated by Next.js (don't edit); this file is for
// project-specific ambient types.

// File is intentionally a *script* (no `import` / `export`):
// - `declare module "*.css"` is treated as ambient module declaration (global)
// - `interface Window { ... }` augments the global Window type
// If you add `export {}` here, TypeScript treats this file as a module and
// both `declare module` and `interface Window` become module-scoped — which
// is why I had to revert that earlier (broke CSS import declarations).

declare module "*.css";

interface Window {
  SpeechRecognition: any;
  webkitSpeechRecognition: any;
}