// AI distractor generation for multiple-choice review.
// Per Frank #6372: instead of fill-in (type the word), the review
// session picks the correct word from 4 options (1 correct + 3 easily-
// confused wrong answers generated by AI).
//
// Strategy: process the entire session in ONE LLM call (batched prompt)
// instead of one call per item — saves N+1 round-trips and keeps the
// ~3s gpt-4o-mini latency to a single pause when /review first loads.
//
// Cost: ~$0.005 per call (gpt-4o-mini, ~400 input tokens for 20 items +
// ~300 output tokens for 60 distractors). Latency: 2-4s typical.

import OpenAI from "openai";

// Lazy OpenAI client — same pattern as examples.ts.
let _openai: OpenAI | null = null;
function getOpenAI(): OpenAI {
  if (!_openai) {
    _openai = new OpenAI();
  }
  return _openai;
}

export type DistractorItem = {
  id: string;
  word: string;
  meaning: string;
  reading: string | null;
  type: string;
};

export type DistractorSet = {
  id: string;
  distractors: string[];
};

const SYSTEM_PROMPT = `You are a Japanese language tutor generating distractors for a multiple-choice quiz. For each vocabulary item given, produce 3 "easily confused" wrong answers — Japanese words a learner might MISTAKENLY pick.

Return JSON:
{
  "items": [
    { "id": "<vocab_id>", "distractors": ["<d1>", "<d2>", "<d3>"] },
    ...
  ]
}

Hard rules (every distractor must satisfy ALL):
- Must be a real Japanese word (no garbage, no romaji, no furigana-only).
- Must be DIFFERENT from the correct answer.
- Must look/sound/mean something similar enough to be a plausible "trap".

Strategies by vocab type (pick what's natural for the word):
- Kanji vocab → prefer same kanji with different reading (e.g. 場合 "ばあい" vs 場外 "じょうがい"), OR homophones, OR same radicals with different second kanji.
- Hiragana/katakana vocab → prefer similar-meaning words OR near-homophones.
- Phrase/grammar → prefer wrong particles / wrong word-order variants / similar-looking forms.

Other rules:
- Return ONLY the JSON object, no markdown fences, no comments.
- 3 distractors per item exactly. No more, no less.
- All strings in plain Japanese (kanji + kana mix as natural), no quotes inside strings.`;

// Generate distractors for an entire batch in one LLM call.
// Falls back to a deterministic placeholder per item if the model
// returns malformed output (so the page never crashes).
export async function generateDistractors(
  items: DistractorItem[]
): Promise<DistractorSet[]> {
  if (items.length === 0) return [];

  const userContent = JSON.stringify({
    items: items.map((it) => ({
      id: it.id,
      word: it.word,
      meaning: it.meaning,
      reading: it.reading,
      type: it.type,
    })),
  });

  let parsed: { items?: Array<{ id: string; distractors: unknown }> } = {};
  try {
    const response = await getOpenAI().chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: userContent },
      ],
      response_format: { type: "json_object" },
      temperature: 0.7,
    });
    const content = response.choices[0]?.message?.content ?? "{}";
    parsed = JSON.parse(content);
  } catch (err) {
    console.error("generateDistractors: OpenAI call failed", err);
    parsed = {};
  }

  const result: DistractorSet[] = [];
  for (const item of items) {
    const set = parsed.items?.find(
      (s) => s && typeof s === "object" && s.id === item.id
    );
    const raw = Array.isArray(set?.distractors)
      ? (set!.distractors as unknown[])
      : [];

    // Filter: keep only non-empty strings different from the correct word.
    const clean: string[] = [];
    const seen = new Set<string>();
    for (const d of raw) {
      if (typeof d !== "string") continue;
      const trimmed = d.trim();
      if (!trimmed || trimmed === item.word) continue;
      if (seen.has(trimmed)) continue;
      seen.add(trimmed);
      clean.push(trimmed);
      if (clean.length === 3) break;
    }
    // Pad with safe placeholder if LLM returned fewer than 3 valid.
    while (clean.length < 3) {
      clean.push(`(${item.word}的干扰项)`);
    }
    result.push({ id: item.id, distractors: clean });
  }
  return result;
}
