// Server-side data access for vocabulary_items.
// Used by Server Components + Server Actions in app/vocabulary/.
//
// All queries rely on the Supabase session cookie (via lib/supabase/server.ts)
// and the RLS policies in supabase/migrations/0003_vocabulary.sql —
// the user_id filter on `eq` is redundant with RLS but kept for clarity.

import { createClient } from "@/lib/supabase/server";
import { enrichVocabulary } from "./vocabulary/enrich";
import { generateExample } from "./vocabulary/examples";
import { ensureReviewRecord } from "./vocabulary/reviews";

export type VocabularyType = "word" | "phrase" | "grammar" | "sentence";

export type VocabularyItem = {
  id: string;
  user_id: string;
  type: VocabularyType;
  word: string;
  reading: string | null;
  meaning: string;
  language: string;
  part_of_speech: string | null;
  level: string | null;
  mastery: number;
  created_at: string;
  updated_at: string;
  // Chrome Extension source tracking (per 0005_chrome_extension.sql
  // migration + docs/0821requirements.docx §10 + §22-§23).
  source: string | null;
  source_url: string | null;
  source_title: string | null;
  source_domain: string | null;
  source_favicon: string | null;
  source_added_at: string | null;
};

export type NewVocabularyItem = {
  type: VocabularyType;
  word: string;
  reading?: string | null;
  // Optional — auto-generated by AI when blank (see lib/vocabulary/enrich.ts).
  meaning?: string;
  language?: string;
  part_of_speech?: string | null;
  level?: string | null;
};

export type VocabularySort = "newest" | "oldest" | "word";

export type ListVocabularyOpts = {
  type?: VocabularyType;
  level?: string;
  search?: string;
  sort?: VocabularySort;
};

export type VocabularyExample = {
  id: string;
  vocabulary_id: string;
  sentence: string;
  translation: string | null;
  reading: string | null;
  is_primary: boolean;
  generated_by_ai: boolean;
  user_edited: boolean;
  created_at: string;
  updated_at: string;
};

// Wrap supabase errors so callers can throw without leaking SDK details.
// Preserves the PostgREST error code (e.g. "23505" for unique_violation)
// on the thrown Error so callers can distinguish user-fixable errors
// (e.g. duplicate word) from transient server failures. Previously the
// code was dropped, so any 23505 surfaced as a generic
// "保存失败，请稍后重试" — misleading users on duplicate adds.
function ensureData<T>(
  res: { data: T | null; error: { message: string; code?: string } | null },
  fallback: T,
): T {
  if (res.error) {
    const err = new Error(res.error.message) as Error & { code?: string };
    err.code = res.error.code;
    throw err;
  }
  return (res.data ?? fallback) as T;
}

export async function listVocabularyItems(
  opts: ListVocabularyOpts = {}
): Promise<VocabularyItem[]> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return [];

  let query = supabase
    .from("vocabulary_items")
    .select("*")
    .eq("user_id", user.id);

  if (opts.type) {
    query = query.eq("type", opts.type);
  }

  if (opts.level) {
    query = query.eq("level", opts.level);
  }

  const q = opts.search?.trim();
  if (q) {
    // Escape single quotes for the .or() filter to avoid breaking PostgREST.
    const safe = q.replace(/'/g, "''");
    query = query.or(
      `word.ilike.%${safe}%,reading.ilike.%${safe}%,meaning.ilike.%${safe}%`
    );
  }

  if (opts.sort === "oldest") {
    query = query.order("created_at", { ascending: true });
  } else if (opts.sort === "word") {
    query = query.order("word", { ascending: true });
  } else {
    query = query.order("created_at", { ascending: false });
  }

  return ensureData(await query, [] as VocabularyItem[]);
}

export async function getVocabularyItem(
  id: string
): Promise<VocabularyItem | null> {
  const supabase = await createClient();
  return ensureData(
    await supabase
      .from("vocabulary_items")
      .select("*")
      .eq("id", id)
      .maybeSingle(),
    null
  );
}

export async function createVocabularyItem(
  item: NewVocabularyItem
): Promise<VocabularyItem> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error("Not authenticated");

  // Auto-fill any missing field via AI. The minimal call is just the word.
  let reading: string | null = item.reading ?? null;
  let meaning: string = item.meaning ?? "";
  let level: string | null = item.level ?? null;
  let partOfSpeech: string | null = item.part_of_speech ?? null;

  const needsEnrichment =
    !meaning || !reading || !level || !partOfSpeech;
  if (needsEnrichment) {
    try {
      const enriched = await enrichVocabulary(item.word, item.type);
      if (!reading && enriched.reading) reading = enriched.reading;
      if (!meaning) meaning = enriched.meaning || item.word;
      if (!level && enriched.level) level = enriched.level;
      if (!partOfSpeech && enriched.part_of_speech)
        partOfSpeech = enriched.part_of_speech;
    } catch (err) {
      // Don't fail the whole insert — fall back to word-as-meaning.
      // The user can edit fields later on the detail page.
      console.error("vocabulary AI enrichment failed:", err);
      if (!meaning) meaning = item.word;
    }
  }

  const inserted = ensureData(
    await supabase
      .from("vocabulary_items")
      .insert({
        user_id: user.id,
        type: item.type,
        word: item.word,
        reading,
        meaning,
        language: item.language ?? "ja",
        part_of_speech: partOfSpeech,
        level,
      })
      .select()
      .single(),
    null as unknown as VocabularyItem
  );

  // Auto-attach a primary example sentence (Phase 3). Don't fail the
  // whole create if AI generation hiccups — user can regenerate later
  // from the detail page (Phase 4 lite).
  try {
    const example = await generateExample({
      word: inserted.word,
      meaning: inserted.meaning,
      reading: inserted.reading,
      type: inserted.type,
    });
    if (example.sentence) {
      const { error: exampleErr } = await supabase
        .from("vocabulary_examples")
        .insert({
          vocabulary_id: inserted.id,
          sentence: example.sentence,
          translation: example.translation,
          reading: example.reading,
          is_primary: true,
          generated_by_ai: true,
        });
      if (exampleErr) {
        console.error(
          "vocabulary example insert failed (vocab created ok):",
          exampleErr,
        );
      }
    }
  } catch (err) {
    console.error("vocabulary example generation failed:", err);
  }

  // Phase 7: queue the new vocab for first-pass review (next_review_at=now).
  // Idempotent — safe to call even if the row already exists. Failure here
  // doesn't break the create — vocab shows up fine, just won't appear in
  // /review until something else enqueues it.
  try {
    await ensureReviewRecord(inserted.id);
  } catch (err) {
    console.error("vocabulary ensureReviewRecord failed:", err);
  }

  return inserted;
}

export async function deleteVocabularyItem(id: string): Promise<void> {
  const supabase = await createClient();
  const { error } = await supabase
    .from("vocabulary_items")
    .delete()
    .eq("id", id);
  if (error) throw new Error(error.message);
}

export async function countVocabularyItems(): Promise<number> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return 0;
  const { count, error } = await supabase
    .from("vocabulary_items")
    .select("id", { count: "exact", head: true })
    .eq("user_id", user.id);
  if (error) throw new Error(error.message);
  return count ?? 0;
}

export async function getPrimaryExample(
  vocabularyId: string
): Promise<VocabularyExample | null> {
  const supabase = await createClient();
  return ensureData(
    await supabase
      .from("vocabulary_examples")
      .select("*")
      .eq("vocabulary_id", vocabularyId)
      .eq("is_primary", true)
      .maybeSingle(),
    null
  );
}

// ==========================================================================
// Per-vocab learning time tracking
// (docs/0830需求.md + Frank #7274/#7276, 2026-08-30).
//
// A: 5s/word cap (replacing #6704's 10s/visit) for /vocabulary/[id].
// B: per-vocab independent (replacing #6696's cross-item cumulative).
// C: DAILY reset baseline — counter rolls over at user's local midnight.
// D: /review unchanged (still uses useSessionTimer with 10s cap).
//
// The atomic increment lives in the migration 0006 RPC
// `increment_vocab_learning_time` (FOR UPDATE row lock + LEAST cap +
// daily-reset branch). This module is the typed wrapper that the
// server actions and the API route call.
// ==========================================================================

export type VocabLearningState = {
  learningTimeMs: number;
  lastViewedAt: string | null;
  state: "IDLE" | "COMPLETED";
};

export async function getVocabLearningState(
  vocabId: string,
  todayDate: string
): Promise<VocabLearningState> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return { learningTimeMs: 0, lastViewedAt: null, state: "IDLE" };
  }

  const { data, error } = await supabase
    .from("vocabulary_items")
    .select("learning_time_ms, learning_date, learning_last_viewed_at")
    .eq("id", vocabId)
    .eq("user_id", user.id)
    .maybeSingle();
  if (error) throw new Error(error.message);
  if (!data) return { learningTimeMs: 0, lastViewedAt: null, state: "IDLE" };

  // Daily reset (per Frank #7276 C): if stored date != client-supplied
  // today, treat the counter as 0 — the cap is "5s per word per day",
  // not "5s per word ever". The client passes its local-today so a
  // JST user's "today" feels right even though the server is in UTC
  // (matches lib/today-stats.todayKey() pattern for daily_rollups).
  const isToday = data.learning_date === todayDate;
  const ms = isToday ? (data.learning_time_ms ?? 0) : 0;

  return {
    learningTimeMs: ms,
    lastViewedAt: data.learning_last_viewed_at,
    state: ms >= 5000 ? "COMPLETED" : "IDLE",
  };
}

export async function recordVocabLearningTime(
  vocabId: string,
  deltaMs: number,
  todayDate: string
): Promise<{ learningTimeMs: number; state: "IDLE" | "COMPLETED" }> {
  if (deltaMs <= 0) {
    // No-op, return current state (avoids an RPC round-trip for
    // zero-duration flushes — see use-vocab-learning-timer MIN_FLUSH_DELTA_MS).
    const cur = await getVocabLearningState(vocabId, todayDate);
    return { learningTimeMs: cur.learningTimeMs, state: cur.state };
  }

  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error("Not authenticated");

  // Atomic increment via RPC — daily reset + 5000ms cap + ownership
  // check all enforced server-side (per docs/0830需求.md §十三).
  // FOR UPDATE row lock inside the RPC prevents two parallel flushes
  // from same user (e.g., two tabs of /vocabulary/A) from racing past
  // the 5000ms cap before either commits.
  const { data, error } = await supabase.rpc(
    "increment_vocab_learning_time",
    {
      p_vocab_id: vocabId,
      p_delta_ms: Math.floor(deltaMs),
      p_user_id: user.id,
      p_date: todayDate,
    }
  );

  if (error) throw new Error(error.message);
  if (!data || !Array.isArray(data) || data.length === 0) {
    throw new Error("increment_vocab_learning_time RPC returned no data");
  }

  const row = data[0] as {
    new_learning_time_ms: number;
    new_state: string;
  };
  return {
    learningTimeMs: row.new_learning_time_ms,
    state: row.new_state as "IDLE" | "COMPLETED",
  };
}
